# Generated by Django 3.2.5 on 2021-07-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='item',
            field=models.CharField(max_length=10),
        ),
    ]
