# Generated by Django 3.2.5 on 2021-10-12 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0006_auto_20211006_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('satisfaction', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('snack_or_meal', models.BooleanField(default=True)),
                ('snack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eats', to='snacks.snack')),
            ],
        ),
    ]
