# Generated by Django 3.2.5 on 2021-10-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0007_eat'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eat',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eat',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
