# Generated by Django 3.2.5 on 2021-10-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0008_auto_20211012_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eat',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='eat',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='eat',
            name='snack_or_meal',
        ),
    ]
