# Generated by Django 3.2.8 on 2021-11-16 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0010_remove_eat_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eats', to='snacks.snack'),
        ),
    ]
