version: '3'

services:
  web:
    build: . 
    command: python ./snackmanager/manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=snackproject
      - DB_USER=postgres
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    image: postgres:latest
    command: pg_ctl -D /var/lib/postgresql/data -l logfile start
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=snackproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
